#ifndef AVALANG_H
#define AVALANG_H

/*
 * AvaLang public C API.
 *
 * This is the ONLY header external bindings (C#, Python, Java, Rust, ...)
 * need to consume. It is plain C (extern "C"), no C++ types cross this
 * boundary, so there is no name-mangling / ABI fragility issue for
 * bindings generated by any FFI toolchain (P/Invoke, ctypes, JNA, etc).
 *
 * Ownership model:
 *   - All Ava*Handle types are opaque pointers owned by the library.
 *   - Callers never allocate or free the internals directly, only via
 *     the matching ava_*_destroy function.
 *   - ava_value_t is a plain-old-data struct (tagged union), safe to pass
 *     by value across the ABI boundary.
 */

#include <stdint.h>
#include <stddef.h>

#ifdef __cplusplus
extern "C" {
#endif

#if defined(_WIN32)
  #define AVA_API __declspec(dllexport)
#else
  #define AVA_API __attribute__((visibility("default")))
#endif

/* ---------------------------------------------------------------------
 * Opaque handles
 * ------------------------------------------------------------------- */

typedef struct AvaVM        AvaVM;        /* one VM instance / isolate   */
typedef struct AvaModule    AvaModule;    /* compiled bytecode module    */
typedef struct AvaCoroutine AvaCoroutine; /* suspendable execution state */

/* ---------------------------------------------------------------------
 * Value type: tagged union passed by value across the ABI.
 * Strings/Lists/Dicts/Functions/Instances are represented by a handle
 * (ref-counted internally); the C API never exposes their raw layout.
 * ------------------------------------------------------------------- */

typedef enum AvaValueType {
    AVA_NIL = 0,
    AVA_BOOL,
    AVA_NUMBER,
    AVA_STRING,
    AVA_LIST,
    AVA_DICT,
    AVA_FUNCTION,
    AVA_INSTANCE,
    AVA_CLASS,
    AVA_COROUTINE,
    AVA_NATIVE,
    AVA_BOUND,
    AVA_EXCEPTION,
    AVA_MODULE
} AvaValueType;

typedef struct AvaRef { uint64_t id; } AvaRef;

typedef struct ava_value_t {
    AvaValueType type;
    union {
        int      b;      /* AVA_BOOL     */
        double   n;       /* AVA_NUMBER   */
        AvaRef   ref;      /* everything ref-counted (string/list/dict/...) */
        AvaRef   err;     /* AVA_EXCEPTION */
    } as;
} ava_value_t;

typedef struct {
    const char* key;
    size_t key_len;
    ava_value_t value;
} ava_dict_pair_t;

/* ---------------------------------------------------------------------
 * Native function callback: how host languages expose functions to
 * scripts. Called by the VM with args already marshalled as ava_value_t.
 * ------------------------------------------------------------------- */

typedef ava_value_t (*AvaNativeFn)(
    AvaVM* vm,
    const ava_value_t* args,
    size_t arg_count,
    void* user_data
);

/* ---------------------------------------------------------------------
 * VM lifecycle
 * ------------------------------------------------------------------- */

AVA_API AvaVM* ava_vm_create(void);
AVA_API void   ava_vm_destroy(AvaVM* vm);

/* Sets the base directory `import` resolves module paths against for
 * ava_compile/ava_run (which take source as a string, not a file path --
 * without this, module resolution falls back to the process's current
 * working directory, which is usually wrong for a host like an editor
 * that runs unsaved-buffer text from an arbitrary file's location).
 * Pass the directory of the file being run (or "" to reset to CWD). */
AVA_API void ava_vm_set_current_dir(AvaVM* vm, const char* dir);

/* Module resolution ("import"), in order:
 *   1. relative to the current script's own directory (ava_vm_set_current_dir)
 *   2. each path added via ava_vm_add_search_path, in the order added
 *   3. the single stdlib path set via ava_vm_set_stdlib_path
 * Neither of the below is set by default; a host that wants a "base
 * modules" folder (shared library-style .ava files, separate from a
 * project's own modules) must call these explicitly. */
AVA_API void ava_vm_add_search_path(AvaVM* vm, const char* path);
AVA_API void ava_vm_set_stdlib_path(AvaVM* vm, const char* path);

/* Returns the currently configured stdlib path ("" if unset). Caller
 * must free the returned string with ava_string_free. */
AVA_API char* ava_vm_get_stdlib_path(AvaVM* vm);

/* Registers a native (host) function under `name`, callable from scripts.
 * `user_data` is passed back unchanged on every call (closure context). */
AVA_API void ava_vm_register_native(
    AvaVM* vm,
    const char* name,
    AvaNativeFn fn,
    void* user_data
);

/* Print sink: called once per `print(...)` call from a running script,
 * with the fully formatted line (arguments space-joined, trailing '\n'
 * included) as `utf8`/`len`. Lets a host UI (e.g. Ava Studio's Output
 * console) capture script output instead of it going to a process's
 * stdout, which a GUI app typically has no visible console for. Pass
 * fn = NULL to restore the default (print writes to stdout). */
typedef void (*AvaPrintFn)(const char* utf8, size_t len, void* user_data);

AVA_API void ava_vm_set_print_callback(
    AvaVM* vm,
    AvaPrintFn fn,
    void* user_data
);

/* Alert/Navigate sinks (08_DESIGNER_VIEW_PLAN.md Fase 6, Anexo 9.17's
 * pendientes 1-2): mismo mecanismo que AvaPrintFn de arriba, un evento
 * por llamada de script a `ui.alert(msg)` / `ui.navigate(route)` (ver
 * core/src/ui/builtins.cpp). Sin callback instalado (fn = NULL, el
 * default), ambos degradan a print sink con un prefijo -- ver
 * VM::Alert/VM::Navigate en core/src/vm/vm.cpp -- así un host que no
 * define ninguno de los dos no pierde silenciosamente lo que el script
 * pidió, solo no actúa sobre eso.
 *
 * ava_vm_set_navigate_callback en particular es un hook GENÉRICO: este
 * repo (motor C++) no tiene noción de rutas/router -- eso vive en el
 * host .NET (AvaLang.UI/Routing/RouteScanner.cs) o en un futuro router
 * de Ava Studio -- así que quien instale este callback es quien decide
 * qué significa "navegar". */
typedef void (*AvaAlertFn)(const char* utf8, size_t len, void* user_data);

AVA_API void ava_vm_set_alert_callback(
    AvaVM* vm,
    AvaAlertFn fn,
    void* user_data
);

typedef void (*AvaNavigateFn)(const char* utf8, size_t len, void* user_data);

AVA_API void ava_vm_set_navigate_callback(
    AvaVM* vm,
    AvaNavigateFn fn,
    void* user_data
);

/* ---------------------------------------------------------------------
 * Compilation
 * ------------------------------------------------------------------- */

/* Compiles source text into a bytecode module owned by the caller.
 * On failure returns NULL and fills out_error (caller must free with
 * ava_string_free) with a human-readable diagnostic. */
AVA_API AvaModule* ava_compile(
    AvaVM* vm,
    const char* source,
    const char* source_name,
    char** out_error
);

AVA_API void ava_module_destroy(AvaModule* module);

/* ---------------------------------------------------------------------
 * Bytecode serialization (.avbc) -- Fase 6 de plan_ava_pack.md.
 *
 * Envuelve compiler/proto_io.h + compiler/obfuscate.h (internos) para que
 * avacli/avapack puedan producir/consumir bytecode precompilado sin incluir
 * ningun header interno del compilador -- ver el comentario de cabecera de
 * ese header para el porque.
 * ------------------------------------------------------------------- */

typedef struct AvaModuleSerializeOptions {
    int strip_debug_info;      /* 1 = no emitir debug_lines/debug_name/source_name */
    int obfuscate;              /* 1 = correr el pase de ofuscacion antes de serializar */
    uint64_t obfuscate_seed;    /* module_seed del pase; ignorado si obfuscate == 0 */
    int obfuscate_strings;      /* 1 = ademas ofuscar los Value::String de la constant pool */
    int flatten_control_flow;   /* 1 = ademas aplanar el control-flow de cada Proto elegible */
} AvaModuleSerializeOptions;

/* Serializa `module` (formato .avbc, ver proto_io.h) a un buffer que el
 * caller debe liberar con ava_string_free. `options` puede ser NULL (usa
 * strip_debug_info=0, obfuscate=0 -- mismos defaults que ProtoIoOptions).
 *
 * IMPORTANTE si options->obfuscate != 0: el pase de ofuscacion corre
 * IN-PLACE sobre el Proto de `module` -- este mismo AvaModule NO debe
 * pasarse a ava_run despues de esta llamada si obfuscate_strings tambien
 * estaba activo (la constant pool queda con strings cifrados, invalidos
 * para GETGLOBAL/GETATTR hasta que se revierta -- ver
 * ava_module_deobfuscate_strings). El flujo esperado es compilar,
 * serializar-con-ofuscacion, y descartar el AvaModule -- no ejecutarlo en
 * el mismo proceso.
 *
 * Si `out_symbol_map` no es NULL, recibe el SymbolMap (texto formateado,
 * "kind\toriginal\tobfuscated" por linea, "" si obfuscate==0 o no hubo
 * simbolos) -- pensado para guardarse LOCALMENTE junto al proyecto fuente
 * del lado del desarrollador (nunca embeberlo en el build distribuido).
 * Liberar con ava_string_free. */
AVA_API uint8_t* ava_module_serialize(
    AvaModule* module,
    const AvaModuleSerializeOptions* options,
    size_t* out_len,
    char** out_symbol_map
);

/* Reconstruye un AvaModule desde bytes producidos por ava_module_serialize
 * (o por proto_io::WriteProto directamente). `vm` no se usa hoy (el Proto
 * reconstruido no depende de ninguna VM en particular) -- se recibe por
 * simetria con ava_compile y por si una version futura de este formato
 * necesita contexto de la VM (ej. validar una version de ABI instalada).
 * Devuelve NULL y llena out_error (liberar con ava_string_free) si `bytes`
 * no es un .avbc valido -- incluyendo version de formato no soportada por
 * este build de avalang (ver proto_io.h: no hay compatibilidad hacia atras
 * entre versiones de formato distintas, se rechaza con error claro). */
AVA_API AvaModule* ava_module_deserialize(
    AvaVM* vm,
    const uint8_t* bytes,
    size_t len,
    char** out_error
);

/* Revierte la ofuscacion de strings de un modulo deserializado (ver
 * AvaModuleSerializeOptions::obfuscate_strings) -- llamar UNA vez, con el
 * mismo obfuscate_seed usado al serializar, inmediatamente despues de
 * ava_module_deserialize y ANTES de ava_run. No-op si el .avbc no fue
 * serializado con obfuscate_strings=1 (aplica un XOR reversible sobre
 * strings que nunca se toco -- corromperia la constant pool, asi que el
 * caller es responsable de no llamar esto sobre un modulo que no lo
 * necesita). */
AVA_API void ava_module_deobfuscate_strings(AvaModule* module, uint64_t seed);

/* ---------------------------------------------------------------------
 * Execution
 * ------------------------------------------------------------------- */

/* Runs the module's top-level code. Returns the last expression value
 * or AVA_NIL. */
AVA_API void ava_run(AvaVM* vm, AvaModule* module, ava_value_t* out_result, char** out_error);

AVA_API void ava_call(
    AvaVM* vm,
    ava_value_t callable,
    const ava_value_t* args,
    size_t arg_count,
    ava_value_t* out_result,
    char** out_error
);

AVA_API ava_value_t ava_get_global(AvaVM* vm, const char* name);
AVA_API void ava_set_global(AvaVM* vm, const char* name, ava_value_t value);

AVA_API ava_value_t ava_import(AvaVM* vm, const char* module_path, const char* alias, char** out_error);

/* ---------------------------------------------------------------------
 * Coroutines
 * ------------------------------------------------------------------- */

AVA_API AvaCoroutine* ava_coroutine_create(AvaVM* vm, ava_value_t function);
AVA_API void          ava_coroutine_destroy(AvaCoroutine* co);

typedef enum AvaCoStatus { AVA_CO_SUSPENDED, AVA_CO_RUNNING, AVA_CO_DEAD } AvaCoStatus;

/* Resumes execution. Writes result values into out_values (caller-owned
 * buffer of out_capacity slots) and the count into out_count. */
AVA_API AvaCoStatus ava_coroutine_resume(
    AvaVM* vm,
    AvaCoroutine* co,
    const ava_value_t* args,
    size_t arg_count,
    ava_value_t* out_values,
    size_t out_capacity,
    size_t* out_count
);

AVA_API AvaCoStatus ava_coroutine_status(AvaVM* vm, AvaCoroutine* co);

/* ---------------------------------------------------------------------
 * Value helpers (construction / inspection of ref-counted values)
 * ------------------------------------------------------------------- */

AVA_API ava_value_t ava_string_create(AvaVM* vm, const char* utf8, size_t len);
AVA_API const char* ava_string_data(AvaVM* vm, ava_value_t str, size_t* out_len);

AVA_API ava_value_t ava_list_create(AvaVM* vm);
AVA_API void         ava_list_append(AvaVM* vm, ava_value_t list, ava_value_t item);
AVA_API size_t       ava_list_length(AvaVM* vm, ava_value_t list);
AVA_API ava_value_t  ava_list_get(AvaVM* vm, ava_value_t list, size_t index);
AVA_API void         ava_list_insert(AvaVM* vm, ava_value_t list, size_t index, ava_value_t item);
AVA_API void         ava_list_remove(AvaVM* vm, ava_value_t list, size_t index);
AVA_API void         ava_list_set(AvaVM* vm, ava_value_t list, size_t index, ava_value_t value);

AVA_API ava_value_t ava_dict_create(AvaVM* vm);
AVA_API void         ava_dict_set(AvaVM* vm, ava_value_t dict, const char* key, ava_value_t value);
AVA_API ava_value_t  ava_dict_get(AvaVM* vm, ava_value_t dict, const char* key);
AVA_API size_t       ava_dict_length(AvaVM* vm, ava_value_t dict);
AVA_API size_t       ava_dict_entries(AvaVM* vm, ava_value_t dict, void** out_entries);
AVA_API int          ava_dict_contains(AvaVM* vm, ava_value_t dict, const char* key, size_t key_len);

/* Ref-counting: any ava_value_t returned to the host that holds a ref
 * (string/list/dict/function/instance/coroutine) must be released when
 * the host is done with it. AVA_NIL/AVA_BOOL/AVA_NUMBER are no-ops. */
AVA_API void ava_value_retain(AvaVM* vm, ava_value_t value);
AVA_API void ava_value_release(AvaVM* vm, ava_value_t value);

AVA_API void ava_string_free(char* s); /* frees strings returned via out_error, etc. */

/* Structured position (1-based; 0 = unknown) of the most recent error
 * caught by ava_compile / ava_run / ava_call / ava_import on this VM --
 * call right after one of those returns a NULL module / fills out_error.
 * Lets a host UI (e.g. Ava Studio's Code Editor) highlight the exact
 * source line/column instead of only showing out_error's formatted text.
 * Runtime errors (from ava_run/ava_call) only carry line-level precision
 * today, so ava_last_error_column returns 0 for those; syntax errors
 * (from ava_compile) carry both. Overwritten by this VM's next such
 * call, so read it before making another one. */
AVA_API int ava_last_error_line(AvaVM* vm);
AVA_API int ava_last_error_column(AvaVM* vm);

/* Path of the source file the most recent error (see above) came from --
 * e.g. an imported module's file when the error happened inside it,
 * rather than the top-level script. Caller owns the returned string and
 * must free it with ava_string_free. Empty (but non-null) when unknown,
 * in which case a host UI should fall back to whichever file it just
 * compiled/ran. Overwritten by this VM's next ava_compile/ava_run/
 * ava_call/ava_import call, so read it before making another one. */
AVA_API char* ava_last_error_source(AvaVM* vm);

/* ---------------------------------------------------------------------
 * UI Component Tree API
 * ------------------------------------------------------------------- */

typedef struct AvaComponent AvaComponent;
typedef struct AvaComponentTree AvaComponentTree;

AVA_API AvaComponentTree* ava_ui_create_tree(void);
AVA_API void               ava_ui_destroy_tree(AvaComponentTree* tree);

AVA_API AvaComponent* ava_ui_create_component(const char* type);
AVA_API void           ava_ui_destroy_component(AvaComponent* component);

AVA_API void ava_ui_set_property(AvaComponent* comp, const char* key, ava_value_t value);
AVA_API int  ava_ui_has_property(AvaComponent* comp, const char* key);
AVA_API ava_value_t ava_ui_get_property(AvaComponent* comp, const char* key);
AVA_API void ava_ui_remove_property(AvaComponent* comp, const char* key);

/* Enumeration by index, in insertion order -- for a caller (e.g. a
 * host's .avaui-text adapter converting an AvaComponent tree into its
 * own node model) that needs to walk every property/event a component
 * has without already knowing the key names ahead of time, unlike
 * ava_ui_get_property/ava_ui_has_property above which require the key.
 * Returns NULL / 0 for an out-of-range index or a NULL component. The
 * returned key string follows the same thread-local-buffer convention
 * as ava_ui_get_id -- copy it before the next ava_ui_* call on this
 * thread if it needs to outlive that call. */
AVA_API size_t ava_ui_property_count(AvaComponent* comp);
AVA_API const char* ava_ui_property_key_at(AvaComponent* comp, size_t index);

AVA_API void ava_ui_add_child(AvaComponent* parent, AvaComponent* child);
AVA_API void ava_ui_remove_child(AvaComponent* parent, AvaComponent* child);
AVA_API size_t ava_ui_child_count(AvaComponent* parent);
AVA_API AvaComponent* ava_ui_get_child(AvaComponent* parent, size_t index);

AVA_API void ava_ui_set_event(AvaComponent* comp, const char* event, ava_value_t callback);
AVA_API int  ava_ui_has_event(AvaComponent* comp, const char* event);
AVA_API ava_value_t ava_ui_get_event(AvaComponent* comp, const char* event);

/* Same enumeration pattern as ava_ui_property_count/key_at above, for
 * the event map instead of properties. */
AVA_API size_t ava_ui_event_count(AvaComponent* comp);
AVA_API const char* ava_ui_event_key_at(AvaComponent* comp, size_t index);

AVA_API void ava_ui_set_id(AvaComponent* comp, const char* id);
AVA_API const char* ava_ui_get_id(AvaComponent* comp);

AVA_API void ava_ui_set_layout(AvaComponent* comp, int layout);
AVA_API int  ava_ui_get_layout(AvaComponent* comp);

AVA_API void ava_ui_set_root(AvaComponentTree* tree, AvaComponent* root);
AVA_API AvaComponent* ava_ui_get_root(AvaComponentTree* tree);

AVA_API const char* ava_ui_get_component_type(AvaComponent* comp);
AVA_API const char* ava_ui_tree_to_json(AvaComponentTree* tree);
AVA_API void ava_ui_json_free(char* json);

/* ---------------------------------------------------------------------
 * .avaui text format (parser/writer for the properties/state/view/
 * code/style syntax described in
 * docs/architecture/17_AVAUI_FILE_FORMAT.md). The on-disk keywords
 * `properties` and `code` replaced the older `metadata`/`methods`
 * names (both still parse, for backward compatibility with existing
 * .avaui files, but are never written back) -- see
 * core/src/ui/avaui_text.h's header comment for the full rationale.
 *
 * Centralizes the grammar here (core/src/ui/avaui_text.{h,cpp}, plain
 * ava::ui::Component underneath, same as ava_ui_create_tree's model)
 * instead of each host re-implementing it -- see that plan doc's
 * section 9.2/9.3 for the reasoning: this used to be duplicated by
 * hand in Ava Studio (C++, avaui_text.cpp under studio/src/design/)
 * and the AvaLang.UI .NET prototype (C#, AvaComponentParser.cs), two
 * ports of the same grammar that could silently drift from each other.
 * Both are expected to migrate to call these two functions instead of
 * keeping their own copy.
 * ------------------------------------------------------------------- */

/* Parses a full .avaui file's text and returns its Component tree --
 * the same AvaComponentTree/AvaComponent model ava_ui_create_tree/
 * ava_ui_create_component already produce, so a caller that already
 * knows how to walk that tree (e.g. via ava_ui_tree_to_json, or the
 * C# ComponentTree.cs binding) needs nothing new to consume the
 * result. The tree's root is a synthetic "page" component whose
 * properties come from the file's `properties` block and whose
 * children are the `view` block's top-level component(s) -- there is
 * no `page` keyword in the file format itself.
 *
 * The other five sections of the file don't fit that Component model,
 * so they come back as separate out-params instead of being force-fit
 * into properties:
 *   out_state_json   -- the `state` block, as a flat JSON object of
 *                        string values, e.g. {"counter": "0"}.
 *   out_imports_json -- the `import "..."` lines, as a flat JSON
 *                        array of strings, in file order. Not resolved
 *                        (no import-resolution wiring exists yet on
 *                        either host -- see the plan doc's section
 *                        9.2 point 1).
 *   out_methods_text -- the `code` block (or the legacy `methods`
 *                        keyword -- both parse into this same
 *                        out-param), verbatim (real AvaLang source,
 *                        e.g. `func OnLoad() ... end`) -- not parsed
 *                        here, ava_compile/ava_run already parse it
 *                        when a host wants to execute it.
 *   out_extends      -- the `extends "layout"` line's layout name, or
 *                        an empty (non-NULL) string when the file
 *                        doesn't extend a layout. First occurrence
 *                        wins if more than one is present.
 *   out_routes_json  -- the `route "/path/{param}"` line(s), as a flat
 *                        JSON array, in file order, e.g.
 *                        [{"template": "/products/{id}", "parameters":
 *                        [{"name": "id", "optional": false,
 *                        "constraint": "int"}]}]. "constraint" is
 *                        omitted from a parameter object when the
 *                        route didn't specify one. Empty array when
 *                        the file declares no routes.
 *
 * Always returns a non-NULL tree and clears out_error -- an
 * unrecognized/garbage file yields a mostly-empty page instead of
 * failing, matching every existing .avaui parser's forgiving
 * behavior. out_error exists for interface symmetry with the rest of
 * this header and any future caller that does want to treat a parse
 * problem as fatal.
 *
 * Every out-param is optional (pass NULL to skip it) and, when
 * non-NULL, is set to a string the caller must free with
 * ava_ui_text_free -- except the returned tree itself, which the
 * caller owns and must release with ava_ui_destroy_tree as usual. */
AVA_API AvaComponentTree* ava_ui_parse_avaui_text(
    const char* text,
    char** out_state_json,
    char** out_imports_json,
    char** out_methods_text,
    char** out_error,
    char** out_extends,
    char** out_routes_json
);

/* Inverse of ava_ui_parse_avaui_text: serializes a Component tree plus
 * the same five side-channel sections back into one complete .avaui
 * file's text. `state_json`/`imports_json`/`routes_json` use the same
 * flat JSON shapes documented above (pass "{}"/"[]"/"[]" or NULL for
 * none); `methods_text` is emitted verbatim inside a `methods ... end`
 * block (pass "" or NULL for none); `extends` is emitted as a leading
 * `extends "..."` line (pass "" or NULL to omit it). Returns a string
 * the caller must free with ava_ui_text_free. */
AVA_API char* ava_ui_write_avaui_text(
    AvaComponentTree* tree,
    const char* state_json,
    const char* imports_json,
    const char* methods_text,
    const char* extends,
    const char* routes_json
);

/* Frees strings returned by ava_ui_parse_avaui_text's out-params and
 * by ava_ui_write_avaui_text. Same pattern as ava_string_free /
 * ava_ui_json_free -- kept as its own function (rather than reusing
 * one of those) so this section of the header is self-contained and
 * a binding doesn't have to guess which free function pairs with
 * which allocator. */
AVA_API void ava_ui_text_free(char* text);

#ifdef __cplusplus
}
#endif

#endif /* AVALANG_H */